openapi: 3.0.0
info:
  title: Project Management API
  version: '1.0.0'
paths:
  /projects:
    get:
      summary: Retrieve list of projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
  /projects/{id}:
    get:
      summary: Retrieve project by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: Project not found
components:
  schemas:
    Project:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
      required:
        - id
        - title
