name: Accessibility Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  a11y-lint:
    name: Accessibility ESLint Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint with a11y rules
        run: npm run lint
        
  a11y-static-analysis:
    name: Static Accessibility Analysis
    runs-on: ubuntu-latest
    needs: a11y-lint
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
        
      - name: Install http-server
        run: npm install -g http-server
      
      - name: Start server
        run: http-server dist -p 8080 &
        
      - name: Wait for server
        run: sleep 5
        
      - name: Run pa11y
        run: npx pa11y-ci --config .pa11yci
        
      - name: Generate accessibility report
        run: |
          mkdir -p reports
          npx pa11y-ci --config .pa11yci --reporter json > reports/a11y-report.json
          
      - name: Upload accessibility report
        uses: actions/upload-artifact@v4
        with:
          name: accessibility-report
          path: reports/a11y-report.json
          retention-days: 30